### ISSUE TITLE
[아이템 12] toString을 항상 재정의하라

### ISSUE THREAD

**Issue by kyupid** [java-piledrivers/effective-java#12]

**Comment by kyupid** [comment]
수재님은 toString을 오버라이딩해서 사용하는 경우는 언제이신가요? 저 같은 경우엔 디버깅은 IDE 디버거로 하는 편이라 잘 사용하진 않는거 같아요

**Comment by smjin0222** [comment]
> 수재님은 toString을 오버라이딩해서 사용하는 경우는 언제이신가요? 저 같은 경우엔 디버깅은 IDE 디버거로 하는 편이라 잘 사용하진 않는거 같아요

실시간으로 디버깅이 필요한 경우엔 IDE를 사용하는것이 편할것 같은데, 특정 상황에서 로그를 남기고 싶을 때는 toString()을 재정의하는게 좋을 것 같습니다! 예를 들면 exception을 처리하는 곳에서 해당 로직에 사용되는 객체에 대한 로그를 적절히 남겨놔야 나중에 문제가 됐을 때 쉽게 파악이 가능할것 같습니다.

**Comment by kyupid** [comment]
아 그렇네요.. 로그찍을 때는 항상 사용해왔었네요 ㅎㅎ

**Comment by Soojae** [comment]
넵 저도 로그 찍을 때 주로 사용하는데, 사실 실무에서 사용을 잘 안합니다. ㅎㅎ

**Comment by dunowljj** [comment]
오늘 미팅중에 'toString의 반환한 값에 포함된 정보를 얻어올 수 있는 API를 제공하자'라는 내용에 대해 논의가 있었는데요.

사실은 제가 말씀드렸던 것에 별 내용은 없습니다.ㅎㅎ;; 보통 API 라고 말하면 클라이언트 서버 간의 통신을 하기 위한 수단을 말하는 걸로 알고있는데요, 저는 그냥 단순하게 `웹에서 계층간의 데이터를 주고받는 상황이 아닌 단순히 내부 비즈니스 로직에서의 경우를 API라고 표현한게 아닐까?`라고 이야기 했던 것입니다. 원래 생각나는 것을 이야기하고 보는 편이라 혼란을 드린게 아닌가 싶네요.


그래도 말이 나온김에 예제코드를 짜보았습니다. `PhoneNumber`객체를 만들었고, 75p에 나온 코드처럼 `toString()`를 만들었습니다. `PhoneBook`은 `PhoneNumber`의 리스트를 가집니다.

`PhoneBook`은 `PhoneNumber`을 `register(PhoneNumber)`로 등록이 가능합니다. 그리고 지정한 areaCode(맨 앞 3자리)를 가진 PhoneNumber만 출력하는 기능만 가지고 있습니다. `PhonNumber`에 get이 없는 필드의 값(preifix, lineNum)을 외부에서 활용하려면, `toString()`에서 잘라서 사용할 수 밖에 없다는 내용입니다.

```
import java.util.ArrayList;
import java.util.List;

public class PhoneBook {
    List<PhoneNumber> numberList;

    public PhoneBook() {
        this.numberList = new ArrayList<>();
    }
    public void register(PhoneNumber phoneNumber) {
        numberList.add(phoneNumber);
    }

    /**
     * 객체에 getter메서드 만들어서 사용하기
     */
    public void printWithAreaCodeByGetter(int areaCode) {
        numberList.stream()
                .filter((phoneNumber) -> areaCode == phoneNumber.getAreaCode())
                .forEach(phoneNumber -> System.out.println(phoneNumber));
    }

    /**
     * toString 파싱해서 사용하기
     * 해당 메서드는 toString을 활용하는 getAreaCodeByUsingToString 메서드를 사용합니다.
     */
    public void printWithAreaCodeByToString(int areaCode) {
        numberList.stream()
                .filter((phoneNumber) -> areaCode == getAreaCodeByUsingToString(phoneNumber))
                .forEach(phoneNumber -> System.out.println(phoneNumber));
    }

    /**
     * PhoneNumber 객체에 가보면, 핃드들이 모두 private으로 설정되어 있는데 getter메서드가 없는 areaCode를 제외한 필드의 값을 받아올 방법이 없습니다
     * 반환된 값을 받아올 api가 없다면 다음과 같이 같이 toString()을 이용할 수 밖에 없습니다.
     * 만약, prefix 혹은 lineNum을 통해 값을 필터링하려면, 이 메서드처럼 toString()에 정해진 포맷에서 substring한 결과를 사용할 수 밖에 없습니다.
     */
    private int getAreaCodeByUsingToString(PhoneNumber phoneNumber) {
        String substring = phoneNumber.toString().substring(0, 3);
        return Integer.parseInt(substring);
    }
}

```

```
public class PhoneNumber {
    private int areaCode;
    private int prefix;
    private int lineNum;

    public PhoneNumber(int areaCode, int prefix, int lineNum) {
        this.areaCode = areaCode;
        this.prefix = prefix;
        this.lineNum = lineNum;
    }

    @Override
    public String toString() {
        return String.format("%03d-%03d-%04d", areaCode, prefix, lineNum);
    }

    /**
     * 이와 같이 getter 혹은 값을 반환해주는 api가 없다면 toString이 유일한 값의 탈출구?가 됩니다.
     */
    public int getAreaCode() {
        return areaCode;
    }
}
```

```
public class Main {
    public static void main(String[] args) {
        int areaCode = 32;
        int prefix = 0;
        int lineNum = 0;


        // 맨 앞 3자리(areaCode)가 적당히 겹치는 100개의 전화번호를 생성합니다.
        PhoneBook phoneBook = new PhoneBook();
        for (int i = 0; i < 100; i++) {
            phoneBook.register(new PhoneNumber(areaCode+(i % 10), prefix + i, lineNum + i));
        }

        // phoneBook.printList();

        System.out.println("======API=====");
        phoneBook.printWithAreaCodeByGetter(areaCode);

        System.out.println();
        System.out.println("======toString=====");
        phoneBook.printWithAreaCodeByToString(areaCode);


        // 출력 결과는 동일합니다. 032가 앞자리인 번호만 출력됩니다.
    }
}
```

수재님이 말씀하신 것처럼 toString()의 포멧에 따라 api의 스펙이 변하게 되는게 문제인 것 같습니다. 필드를 추가해서 포멧이 바뀌는 경우도 api가 예상치 못한 오류를 발생시키겠네요.

사실 비즈니스 로직에서 필터링을 할 경우는 거의 없을거라 예상을 하고, 그래서 적절한 예시는 아닌 것 같아요. 
toString을 잘라서 사용할지도 의문이긴 합니다만... 드물게 이렇게 잘라서 사용한 코드가 어딘가 남아있을지도 모를거란 생각은 듭니다.

**Comment by kyupid** [comment]
![2022-10-23_14-49-50](https://user-images.githubusercontent.com/59721293/197376409-581e1ceb-0c29-4693-b115-86f4bb0cf0b5.jpg)

@dunowljj
너무 당연한거라고 생각을 해서 이해를 못하고 있었는데 설명을 자세히 해주셔서 덕분에 위에 글이 무슨 말을 하려는건지 알았습니다. 

toString 에 있는 정보를 파싱해서 사용하려고 하지말고 getter를 만들어라 이말이군요.. 항상 필드 private으로두고 getter를 당연하게 써왔으니까 오히려 엥? 스러운 상황이었던거 같아요.

그리고 중요한 건 아니지만 getPrefixByUsingToString 라는 메소드는 areaCode를 불러오니 getAreaCodeByUsingToString 으로 변경되어야하는거 맞죠? ㅎㅎ

**Comment by dunowljj** [comment]
@kyupid  
헉.. 맞습니다. 코드 수정이 덜 되었네요.
심각한 오류 같습니다.. 코드 보다가 헤매셨다면 사과드립니다. 수정해놓을게요!
