### ISSUE TITLE
[아이템 19] 상속을 고려해 설계하고 문서화하라. 그러지 않았다면 상속을 금지하라

### ISSUE THREAD

**Issue by kyupid** [java-piledrivers/effective-java#19]

**Comment by kyupid** [comment]
122p 첫번째 문단

Q) 프로그래머 통제 밖에 있는 "외부" 란 어떤 걸 의미하는지 코드랑 같이 표현해주실 수 있나요?

**Comment by kyupid** [comment]
122p 2번쨰 문단

Q) 재정의 가능 메서드라는 말이 나와서 궁금한게 있습니다. 사실 abstract class 나 interface 가 아닌 일반 class의 메서드도 재정의가 가능한데, 굳이 abstract class나 interface를 사용해야하는 이유가 있을까요?

**Comment by kyupid** [comment]
123p 2번쨰 문단

Q) 상속이 왜 캡슐화를 헤친다고 하는 것일까요?

**Comment by dunowljj** [comment]
### 122p 첫번째 문단 
Q1) 프로그래머 통제 밖에 있는 "외부" 란 어떤 걸 의미하는지 코드랑 같이 표현해주실 수 있나요?

아무래도 122p에 "프로그래머의 통제권 밖에 있어서 언제 어떻게 변경될지 모른다." 라는 설명 그대로 이해해야할 것 같아요. 사실 해당 부분이 item 18에 관한 요약에 해당하는 설명이라서 해당 부분에서 힌트를 얻을 수 있을 거 같습니다. (item 18의 114p 첫 문단에도 보면 "상위 클래스와 하위 클래스를 모두 같은 프로그래머가 통제하는 패키지 안에서라면 상속도 안전한 방법이다." 라는 문구가 있습니다.)

item 18에서는 "통제 불가능한" 구체 클래스를 상속했을때,생기는 문제점들이 나옵니다. 해당 아이템의 첫 예시에서 구체 클래스인 HashSet을 상속하여 구현한 경우를 보시면 HashSet은 자바에서 지원하는 기능이니 저희 같은 사용자가 직접 관리하거나 수정할 수 없습니다. **새로운 릴리즈가 나오고 변경이 생기는 것이 "외부"에 달려있기 때문에** 변경을 예측할 수 없어서 그 여파로 여러가지 문제가 생기는 것이죠. 결국 쓰여진 그대로 "통제권이 없는 것"을 "외부"라고 생각합니다.

정리하면, 직접 만들고 변경을 통제하는 부분을 내부, 통제 불가능한 부분을 외부로 생각했습니다. 코드로는 어떻게 표현해야할지 잘 떠오르지가 않는데요... 결국 다른 사람이 통제하는 것은 모두 외부가 아닐까 싶습니다.

---

### 122p 2번쨰 문단
Q2) 재정의 가능 메서드라는 말이 나와서 궁금한게 있습니다. 사실 abstract class 나 interface 가 아닌 일반 class의 메서드도 재정의가 가능한데, 굳이 abstract class나 interface를 사용해야하는 이유가 있을까요?

일반 class를 상속하여 재정의할 수 있는데, 굳이 추상클래스나 인터페이스를 사용해야하는 이유를 묻는것으로 이해하면 될까요? 

추상클래스는 사실 클래스와 큰 차이가 없습니다.  다른 점은 **추상클래스**는 인스턴스를 생성할 수 없고, 미완성 메서드인 추상 메서드를  0개 이상포함하고 있습니다. **인터페이스**는 추상화 정도가 더 높아 상수와 추상메서드밖에 가질 수 없습니다.

아무래도 클래스와 추상클래스나 인터페이스의 큰 차이는 추상메서드인 것 같아요. 다형성을 활용하거나, 구현을 강제하기 위해 추상클래스나 인터페이스를 사용한다고 생각합니다 . 클래스를 상속하는 경우에 메서드를 재정의할 수는 있지만 재정의를 꼭 해야하는 것은 아닙니다. 하위클래스에 상위클래스의 메서드와 같은 기능의 메서드가 있는데, 이름은 다르다면 혼동이 올 수 있을 것입니다.

추상클래스나 인터페이스는 추상메서드로 하위클래스에게 구현을 강제할 수 있기 때문에 설계도와 같은 역할을 합니다. 하위클래스에 구현의 책임이 생깁니다.  코드에 통일성이 생기고, 기능을 예측하기도 쉽습니다.

뭉뚱그려 말씀드렸는데, 추상클래스와 인터페이스에 대해서 설명할 것이 정말 많습니다. 사실 이 질문을 받고나서 제 기초가 매우 부족함을 느끼고 반성하고 있습니다. 막상 설명을 하려니 모르는 부분이 많음을 깨달아가네요. 그래서 이 질문에 대해서는 조만간 제대로!! 다시 정리해보겠습니다.

---
### 122p 2번째 문단
Q3) 상속이 왜 캡슐화를 해친다고 말할까요?


질문에 대한 답은 114p에  2번째 문단에 나와있긴 합니다만... "매소드 호출과 달리 상속은 캡슐화를 깨뜨린다. 다르게 말하면, 상위 클래스가 어떻게 구현되느냐에 따라 하위 클래스의 동작에 이상이 생길 수 있다. 상위 클래스는 릴리스마다 내부 구현이 달라질 수 있으며..." 라고 나와 있습니다. 

저도 사실 이부분을 읽으면서, 캡슐화랑 상위 클래스의 구현이 하위클래스에 영향을 주어 변경이 생기는 것이 무슨 관계일까? 라는 고민을 하고 있습니다. 사실 너무 깊게 생각한것인지... 아직도 정확히 모르겠습니다.😂

추측을 하자면, item 18의 120p에 3번째 문단을 보면, Properties에서 Hashtable 상속을 하면 Hashtable로부터 물려받은 메서드에 접근하게 되면서 문제가 생기는 경우를 이야기합니다. 상속을 하면서 상위클래스의 메서드가 노출되는 것 자체가 내부 구현의 노출이라고 보는게 아닐까 생각하고 있습니다.
