### ISSUE TITLE
[아이템 02] 생성자에 매개변수가 많으면 빌더를 고려하라

### ISSUE THREAD

**Issue by kyupid** [java-piledrivers/effective-java#2]

**Comment by kyupid** [comment]
19p 에 있는 `abstract static class Builder<T extends Builder<T>>` 이 부분에 대해서 간단하게 설명해주시면 좋을거 같아요. 그냥 빌더 패턴을 만들때는 이해가 가지만 상속이 하여 빌더를 사용하니까 그 과정이 잘 이해가 가지가 않네요.

**Comment by songinyong** [comment]
추상 클래스는 객체로 만들 수 없어서 제네릭으로 추상 클래스롤 구현한 자식 클래스의 Builder 객체를 받아와
해당 클래스를 구현하기 위해서라고 이해했습니다.

코드 2-4에 말씀하신 부분이 나와있는데 처음 보기에는 어려워보이지만 
extends Builder<T>는 제네릭 타입에 오직 자신을 상속받은 타입만 들어오도록 제한하기 위해 걸린것입니다.
(코드에서 extends Builder<T>를 제외하고 보면 class Builder<T>로 extends 뒤의 Builder<T>와 동일한걸 알 수 있습니다.)

즉 제네릭으로는 오직 추상클래스인 자기 자신을 상속받은 (extends Builder<T>) 타입만을 받을 수 있음을 뜻하며
코드 2-5, 2-6 모두 추상 클래스를 구현한 Builder을 제네릭 타입으로 지정한것을 확인할 수 있습니다.

* 내부클래스 static을 붙이는 이유는 아이템24에 나아있습니다
