### ISSUE TITLE
[아이템 21] 인터페이스는 구현하는 쪽을 생각해 설계하라

### ISSUE THREAD

**Issue by kyupid** [java-piledrivers/effective-java#21]

**Comment by dunowljj** [comment]
138p의 5번째 문단을 보면,
"한편, 디폴트 메서드는 인터페이스로부터 메서드를 제거하거나 기존 메서드의 시그니처를 수정하는 용도가 아님을 명심해야 한다." 
라는 내용이 있습니다. 어떻게 디폴트 메서드로 메서드를 제거하거나 시그니처를 수정한다는 걸까요?

**Comment by smjin0222** [comment]
> 138p의 5번째 문단을 보면, "한편, 디폴트 메서드는 인터페이스로부터 메서드를 제거하거나 기존 메서드의 시그니처를 수정하는 용도가 아님을 명심해야 한다." 라는 내용이 있습니다. 어떻게 디폴트 메서드로 메서드를 제거하거나 시그니처를 수정한다는 걸까요?

인터페이스에 기존에 정의 된 추상메서드와 같은 이름의 디폴트 메서드를 정의하는식으로 사용하지말라는 의미 아닐까요!?

예를 들어, A 인터페이스에 a라는 추상메서드를 정의해놨는데, 나중에 보니 a 추상메서드의 사용법이 조금 달라져서 메서드의 시그니처를 변경하고 싶은 상황이 발생한다고 가정해보겠습니다. 
이 때, 추상메서드의 시그니처를 직접 변경해버리면 기존 구현체들에 전부 문제가 생길 수 있으니 "같은 이름의 디폴트 메소드를 하나 만들어두자!" 라고 판단할 수도 있을것 같습니다.
이러면 추후 새로운 구현객체를 만들 때도 여전히 기존의 추상메서드를 구현해야하고(강제되어있으니), 구현하는 입장에선 같은 이름의 디폴트 메서드가 있으니 혼란이 있을 수도 있을 것 같습니다. 물론 클라이언트 코드에서도 둘 중 어떤 메소드를 사용해야 되는지도 헷갈릴 수 있고요..

이렇게 설명하면 메서드를 제거한다는 부분은 설명이 좀 어렵기도 하네요ㅎㅎ.. 제가 약간은 억지로 껴맞춘것 같기도 한데 다른분들 의견도 궁금합니다!

**Comment by dunowljj** [comment]
그런 방법이 있었군요! 말씀을 듣고 생각해보니, 해당 인터페이스를 구현하지 않았다가 (디폴트 메서드를 이용한) 변경 후에 구현하는 클래스 입장에서는 '제거'라고도 볼 수 있을것 같아요.

다른 분들의 의견도 궁금합니다!
