### ISSUE TITLE
[아이템 22] 인터페이스는 타입을 정의하는 용도로만 사용하라

### ISSUE THREAD

**Issue by kyupid** [java-piledrivers/effective-java#22]

**Comment by kyupid** [comment]
상수는 enum이나 항상 클래스 안에 선언해왔는데, 상수 인터페이스를 선언하지 마라는 논제부터 정말 생소하네요.

관련하여 정리된 블로그 글 첨부합니다

https://camel-context.tistory.com/58

**Comment by mybloom** [comment]
enum이 jdk1.5에 추가되었는데 상수 인터페이스는 enum이 없었을 때 종종 사용했다고 하더라구요.
