### ISSUE TITLE
[아이템 26] 로 타입은 사용하지 말라 

### ISSUE THREAD

**Issue by kyupid** [java-piledrivers/effective-java#26]

**Comment by kyupid** [comment]
List와 List\<Object>의 차이점이 잘 이해가 안가요.

List\<String>은 로 타입인 List의 하위 타입이지만 List\<Object>의 하위 타입은 아니라고 하는데 List의 하위 타입이라면 extend 하거나 impl 해야한다는 말이 아닌지 여기에서 하위타입이라는 말이 잘 이헤가 안가네요.

**Comment by mybloom** [comment]
책에 아래 내용이 나오는데 어떤 의미인지 찾아봐야 할 것 같아요. `아무것도 할 수 없는 것 같은데 왜 쓰는거지?` 란 생각이 들었습니다.

`Collection<?>`는 null외에는 어떤 원소도 넣을 수 없고, 컬렉션에서 꺼낼 수 있는 객체의 타입도 알 수 없다.

**Comment by dunowljj** [comment]
`Collection\<?>는 null외에는 어떤 원소도 넣을 수 없고, 컬렉션에서 꺼낼 수 있는 객체의 타입도 알 수 없다.` 

이 부분에 대해서 비슷한 예시코드를 작성해봤습니다.

<img width="435" alt="image" src="https://user-images.githubusercontent.com/92416661/201099011-59bf45a1-4f25-4103-8947-5602655d4e2a.png">

이미지를 보면,
- `비한정적 와일드카드 타입인 s1`의 경우에는 null값 외에는 원소를 넣을수가 없습니다. 
- 반면, `로 타입인 s2`는 타입 안정성이 보장되지 않고, 아무 타입이나 넣을 수 있습니다.

 null 값 외에는 원소를 넣을 수 없는 이유는 매개변수 `Set<?>`의 경우에는 메서드의 인수를 받기 전까지는 타입을 알 수 없기 떄문입니다.  저는 `<?>` 요놈 자체를 "아직 어떤 타입을 넣을지 모르는데, 이 타입이 들어오는 순간 이 타입으로 제한하겠어!" 라고 보았습니다.

<img width="353" alt="image" src="https://user-images.githubusercontent.com/92416661/201100023-8c9b7d20-377b-4a1d-b663-8a696e284614.png">

더해서 위처럼 다른 메서드에서 `testWildCard(Set<?> s1, Set s2)`를 호출할때, `Set<Integer>` 타입인 `set1`이 `Set<?>  s1` 위치에 인수로 주어집니다. 그 순간 해당 메서드의 `<?>`는 모두 `<Integer>`로 지정된다고 생각해보시면 좋을 것 같아요.

"하위 타입"이라는 표현에 대해서는 저도 더 생각해봐야 할 것 같습니다. 설명이 많이 부족하니 틀린 부분이나 이해가 안가는 부분은 말씀해주세요!

**Comment by dunowljj** [comment]
이미 다들 아시겠지만... 코멘트를 아주 잘못남긴것을 깨닫고 추가로 내용을 조금 남겨봅니다. ㅠㅠ 잘못된 정보 전달 죄송합니다!

\<?>의 경우 \<? extends Object>와 같은 의미로 upper bound를 제시해주는 역할이라고 합니다. 이를 이용해 제네릭 타입에 다형성을 적용할 수 있습니다.
\<E extends Object>의 경우는 지정할 수 있는 타입의 종류를 제한해줍니다.

~~설명이 많이 틀렸습니다. 사죄드립니다.공부를 다시해서 돌아오겠습니다. 위에 코멘트는 잊어주세요..~~ 

다시보니 이전 코멘트의 내용에서 틀린건 없어 보입니다.(?) 정확히 말씀드리면 제가 \<E>와 \<?>의 차이를 완전히 이해하지 못한채로 쓴 글이라 잘못되었을거라 짐작했습니다. 혼선의 혼선 죄송합니다. 😂  내일 미팅때 더 자세한 이야기를 나눠보는걸로..
