### ISSUE TITLE
[아이템 03] private 생성자나 열거 타입으로 싱글턴임을 보증하라

### ISSUE THREAD

**Issue by kyupid** [java-piledrivers/effective-java#3]

**Comment by kyupid** [comment]
24p 유일한 인스턴스를 반환하던 팩터리 메서드가 호출하는 스레드별로 다른 인스턴스를 넘겨주게 할 수 있다는 말이 어떤 의미일까요? 제가 보기엔 public 필드 싱글톤이랑 똑같아 보이네요

**Comment by kyupid** [comment]
리플렉션에 대해서 기본적인 사항들 정리하고 넘기는 것도 좋을거 같아요

**Comment by mybloom** [comment]
> 턴스를 반환하던 팩터리 메서드가 호출하는 스레드별로

메서드가 제공하는 인스턴스가 굳이 싱글턴일 필요가 없다는 의미라 생각합니다.
`getInstance() { new Elivs(); }`  로 메서드를 구현할 수 있으니깐요.
