### ISSUE TITLE
[아이템 50] 적시에 방어적 복사본을 만들라

### ISSUE THREAD

**Issue by kyupid** [java-piledrivers/effective-java#51]

**Comment by Soojae** [comment]
# Bound vs Unbound 메서드 참조
Bound 메서드 참조는 특정 객체 또는 클래스에 바인딩 된 것이고, Unbound 메서드 참조는 특정 객체, 클래스에 바인딩 되지 않는 것을 의미한다.

```java
 // Bound 메서드 참조
 String str = "Hello, world!";
 Function<Integer, Character> charAt = str::charAt;
 System.out.println(charAt.apply(0)); // H

 // Unbound 메서드 참조
 IntFunction<String> valueOf = String::valueOf;
 System.out.println(valueOf.apply(123)); // 123
```
첫번째 예시에서, charAt 메서드는 str 객체에 바인딩 된다. 즉, charAt 객체에서 적용 메서드를 호출하면 str 객체에서 메서드가 호출된다.

두 번째 예에서 valueOf 메서드 참조는 바인딩되지 않는다. 이는 valueOf 메서드가 호출될 때, 메서드에 인수로 전달되는 객체에서 호출됨을 의미한다.

Bound 메서드 참조는 일반적으로 특정 객체에서 메서드를 호출하려는 경우에 사용되는 반면, UnBound 메서드 참조는 일반적으로 메서드를 다른 메서드의 인수로 전달하고 다른 객체에서 호출하도록 하려는 경우(mapping and filter functions in stream pipelines)에 사용된다.

**Comment by kyupid** [comment]
Unbound 메소드 신기하네요..미팅에서 설명을 더 들어보고 싶습니다
