### ISSUE TITLE
[아이템 06] 불필요한 객체 생성을 피하라

### ISSUE THREAD

**Issue by kyupid** [java-piledrivers/effective-java#6]

**Comment by kyupid** [comment]
33p 3번째,4번째 문단에서 어댑터를 예시로 드는데, 어댑터가 무엇인지 간략히 알려주시면 좋을거 같아요
어댑터가 실제 작업은 뒷단 객체에 위임한다는 말이 저는 잘 이해가 안가네요

**Comment by kyupid** [comment]
다들 "유한 상태 머신" 이라는 것이 낯설지 않을까 생각이 드는데요.
https://github.com/java-squid/effective-java/issues/6#issuecomment-696519565 해당 부분에서 설명이 잘 되어있습니다
참고하시면 될것 같아요
난이도가 좀 높아보이네요...😅

**Comment by jellas** [comment]
어댑터는 저희가 흔히 아는 어댑터라고 생각하면 됩니다. 
_(어댑터: 다른 전기나 기계 장치를 서로 연결해서 작동할 수 있도록 만들어 주는 결합 도구)_
자바에서는 **뷰와 데이터(뒷 단)를 연결 해주는 결합도구**라고 쉽게 생각하면 됩니다.


'어댑터가 실제 작업은 뒷 단 객체에 위임한다. 즉 뒷 단 객체 외에는 관리할 상태가 없다. 
```
//뒷 단에 데이터를 넣는다
Map<String,String> death = new HashMap<>();
death.put("hell", "good");
death.put("heaven", "bad");

//어댑터를 여러개 만든다
Set<String> ch1 = death.keySet(); 
Set<String> ch2 = death.keySet();
//=>우린 보통 이럴 때 매번 '새로운' set 인스턴스가 만들어지리라고 생각하지만 매번 같은 Set 인스턴스를 반환할지도 모른다
//(쉽게 말해서 ch1 과 ch2는 별개의 인스턴스일 것이라고 생각)

//과연 두 개는 별개의 인스턴스일지 테스트
ch1.remove("hell"); //ch1에 키 값을 지우기

//뷰 확인(keySet)
System.out.println(ch2.size()); //ch1이 아니 다른 ch2로 확인해보기  
//결과:1 =>같은 Set 인스턴스를 반환한걸 확인할 수 있다


//뒷 단 데이터(map)를 확인
System.out.println(death.size()); 
//결과:1=>map객체 안에 size도 1로 줄어들은것을 알 수 있다
```

즉, 우리는 Set(어댑터)를 여러개 만들어줄 필요 없이 한번만 만들어주면 된다.

이렇게 이해했습니다 틀린 부분이 있으실 언제든 지적해주세요.
