### ISSUE TITLE
스터디 총 회고

### ISSUE THREAD

**Issue by kyupid** [java-piledrivers/effective-java#61]
아래 사항을 코멘트에 남겨주세요. 1번 2번은 공통사항이고 3번은 다음 스터디에 참여하시는 분들이 남겨주세요.

---

(공통사항)

1. 목표: 처음 스터디를 시작할 때 무엇을 성취하기를 바라셨나요? 그 목표를 얼마나 잘 달성하셨나요?

2. 강점,약점,개선점: 저희가 스터디를 하면서 그룹 또는 그룹원들의 어떤 점이 잘 진행되었다고 생각하시나요? 어떤 점을 개선할 수 있었을까요? 예를 들면 더 나은 조직화, 더 많은 토론들, 더 효율적으로 시간 활용 등..

---

(다음 스터디에 참여하시는 분들 항목)

3. 어떻게 하면 모던 인 자바 스터디가 더 유용한 시간이 될 수 있을까요? 다음 스터디에서 바라는 점이 있으신가요?

**Comment by kyupid** [comment]
(공통사항)

목표: 처음 스터디를 시작할 때 무엇을 성취하기를 바라셨나요? 그 목표를 얼마나 잘 달성하셨나요?

무조건적으로 끝까지 전체적으로 일독하는게 목표였습니다. 짧은 페이지에 많은 토픽들이 들어 있어서 혼자 완주하기는 굉장히 어렵다고 생각했었기 때문이거든요. 결국엔 전부 읽긴했는데 아쉬웠던 점은 제가 맡은 담당 부분 외에는 그렇게 제대로 읽어보지 못해서 아직 훑어본 느낌만 들긴합니다. 그래도 한번 완주하는게 애초에 목표였으니 그 부분에 대해서는 충분히 만족합니다.

강점,약점,개선점: 저희가 스터디를 하면서 그룹 또는 그룹원들의 어떤 점이 잘 진행되었다고 생각하시나요? 어떤 점을 개선할 수 있었을까요? 예를 들면 더 나은 조직화, 더 많은 토론들, 더 효율적으로 시간 활용 등..

일단 첫째주부터 시작해서 모든 구성원분들이 꾸준히 다같이 개인사정으로인한 불참외에는 다들 열심히 해오신거 같아 스터디가 잘 진행되었다고 생각합니다. 스터디때 적극적으로 소통하시는 몇몇분들 덕분에 더 좋았던 스터디였습니다. 아쉬웠던점은 반대로 성향차이일수도 있지만 발표외에는 많은 참여가 없었던 분들도 있었던게 아쉬웠네요. 뭔가 장치를 마련한다거나 규율을 정해서 참여도를 끌어낼수도 있었을 거라는 생각에 더 아쉽긴하네요. 다시 첨부터한다면 이런점들을 상기해서 진행하면 더 좋을것 같단생각입니다.

**Comment by mybloom** [comment]
(공통사항)

목표: 처음 스터디를 시작할 때 무엇을 성취하기를 바라셨나요? 그 목표를 얼마나 잘 달성하셨나요?

이펙티브 자바엔 어떤 내용이 있길래 다들 읽을까가 궁금해서 시작한 스터디였습니다. 한 번 훑어보는 것에서는 달성했다고 생각합니다. 
처음에 이 책이 지금 시기에 읽어야할 책인가 고민이 되었었는데요. 한 번 전체적으로 훑으면서 시야가 넓어지기도 했습니다. 그런 부분은 앞으로 개발자로서 어떤 방향을 잡을지 생각할 수 있는 기회가 되었구요. 

강점,약점,개선점: 저희가 스터디를 하면서 그룹 또는 그룹원들의 어떤 점이 잘 진행되었다고 생각하시나요? 어떤 점을 개선할 수 있었을까요? 예를 들면 더 나은 조직화, 더 많은 토론들, 더 효율적으로 시간 활용 등..

4개월간의 스터디와 멤버가 끝까지 유지되었네요! 모두 감사합니다!
중간 중간 실무에서의 경험을 공유해주신 점. 잘 정리된 발표 자료와 설명을 공유한 부분 덕분에 이 책을 흥미롭게 읽을 수 있었습니다. 
다음에 다시 읽게 된다면 주변 개념에 대한 설명과 코드 레벨을 따라가면서 발표하는 것도 좋을 것 같습니다.

**Comment by dunowljj** [comment]
(공통사항)

목표: 처음 스터디를 시작할 때 무엇을 성취하기를 바라셨나요? 그 목표를 얼마나 잘 달성하셨나요?

이펙티브 자바는 꼭 읽으라는 말을 많이 들어서 항상 벼르고 있었는데, 양이 많아서 부담이 되더라구요. 그래서 스터디를 구하게 되었고, 꾸준히 일정시간을 할애해서 완독을 목표로 했습니다. 끝까지 마무리 했으니 목표는 잘 달성한거 같네요 ㅎㅎ

90개나 되는 item들을 언제 다 읽을까 싶었는데 4개월이 금방 갔네요. 그동안 다들 고생하셨습니다!👍

---
강점,약점,개선점: 저희가 스터디를 하면서 그룹 또는 그룹원들의 어떤 점이 잘 진행되었다고 생각하시나요? 어떤 점을 개선할 수 있었을까요? 예를 들면 더 나은 조직화, 더 많은 토론들, 더 효율적으로 시간 활용 등..

현업에서 일하시는 분들에게 각 분야의 이야기를 들을 수 있는 점이 좋았습니다. 서로 부담을 주지 않고 스스로 꾸준히 참여하는 분위기도 좋았습니다. 돌아보니 저 스스로가 시간을 많이 할애하지 못해서 아쉽네요. 후반에는 미팅 전날 그날 분량을 허겁지겁 마무리한 적도 많은 것 같아요. 직장인 분들이 가능하다면, 모임 주기를 주 2회로 진행해서 조금더 긴장감을 주는 것도 좋을 것 같습니다.

**Comment by Soojae** [comment]
목표: 
그 동안 회사 일 때문에 바쁘다는 핑계로 공부를 소홀히 했었습니다. 그래서 이 스터디를 통해 공부 습관을 다시 들이는 것이 목표였습니다.
개인적으로 목표는 잘 달성했지만, 이펙티브 자바는 개인적으로 다시 한번 더 읽어봐야 할 것 같습니다.

강점,약점, 개선점: 
스터디 후반부터 토픽에 관한 이야기도 많이 하고 잘 진행된 것 같습니다. 다만 초반에는 많은 이야기를 못 나눴던 것이 아쉽습니다.
스터디의 깊이와 양은 딱 적당했던 것 같습니다. 깊게 들어가고 싶은 부분들은 개인적으로 찾아보면 되고, 분량도 부담이 안돼서 적당 했다고 생각합니다.


모던 인 자바 스터디: 
이번 스터디랑 똑같은 방식으로 이어가면 좋을 것 같습니다.  그런데 오전 10시에 스터디 하는게 은근 애매하네요?? 약속이 12시 전에 잡히면 참석이 불 가능하더라구요.  아예 8시나 9시로 앞 당기는 것도 좋을 것 같습니다. (아니면 미라클 모닝 느낌으로 7시…)
