### ISSUE TITLE
[아이템 07] 다 쓴 객체 참조를 해제하라

### ISSUE THREAD

**Issue by kyupid** [java-piledrivers/effective-java#7]

**Comment by kyupid** [comment]
- 엔트리
- WeakHashMap
- 콜백 등록 후 해제
- 약한 참조 (weak reference)

저는 너무 낯선 키워드들이네요.

**Comment by kyupid** [comment]
리스너와 콜백에 이 어떤 차이점을 가지는지 이야기 나눠보면 좋을것 같습니다

**Comment by sangminJin** [comment]
1. 엔트리는 Map 컬렉션의 키와 값 한쌍으로 이루어진 요소들을 말하는 것 같습니다! 예시로 Map 컬렉션의 entrySet() 메소드를 이용하여 Map 내부에 있는 엔트리 즉, 키와 값들을 전부 가져올 수 있습니다.

2. 저도 WeakHashMap을 처음봐서 조금 찾아보았는데요. HashMap과는 달리 WeakHashMap은 Key값이 더 이상 사용되지 않는다고 판단되면 다음 GC때 해당 Key, Value 쌍을 제거하는 Map이라고 합니다. 4번의 약한참조와 함께 이해하면 좋을 것 같습니다.
출처 ) https://blog.breakingthat.com/2018/08/26/java-collection-map-weakhashmap/

참고로 위 출처에서 예시로 든 코드가 아래와 같은데

`public class WeakHashMapTest {
    public static void main(String[] args) {
        WeakHashMap<Integer, String> map = new WeakHashMap<>();
        Integer key1 = 1000;
        Integer key2 = 2000;
        map.put(key1, "test a");
        map.put(key2, "test b");
        key1 = null;
        System.gc();  //강제 Garbage Collection
        map.entrySet().stream().forEach(el -> System.out.println(el));
    }
}`

결과
`2000=test b`

위 코드의 WeakHashMap을 HashMap으로 바꾼 경우에는 key1을 더 이상 사용하지 않음에도 불구하고
결과는
`1000=test a
 2000=test b`
로 나오게 됩니다!


3. 책에서는 리스너와 콜백을 거의 동일시 얘기하고 있는 것 같습니다. 리스너 혹은 콜백이 메모리 누수의 주범이라고 얘기하고 있는데 이 부분은 예시가 없어서 저도 조금 어렵네요ㅠㅠ 좀 더 공부해보겠습니다.

**Comment by smjin0222** [comment]
1. 엔트리는 Map 컬렉션의 키와 값 한쌍으로 이루어진 요소들을 말하는 것 같습니다! 예시로 Map 컬렉션의 entrySet() 메소드를 이용하여 Map 내부에 있는 엔트리 즉, 키와 값들을 전부 가져올 수 있습니다.

2. 저도 WeakHashMap을 처음봐서 조금 찾아보았는데요. HashMap과는 달리 WeakHashMap은 Key값이 더 이상 사용되지 않는다고 판단되면 다음 GC때 해당 Key, Value 쌍을 제거하는 Map이라고 합니다. 4번의 약한참조와 함께 이해하면 좋을 것 같습니다.

출처 ) https://blog.breakingthat.com/2018/08/26/java-collection-map-weakhashmap/

참고로 위 출처에서 예시로 든 코드가 아래와 같은데

```java
public class WeakHashMapTest {
    public static void main(String[] args) {
        WeakHashMap<Integer, String> map = new WeakHashMap<>();
        Integer key1 = 1000;
        Integer key2 = 2000;
        map.put(key1, "test a");
        map.put(key2, "test b");
        key1 = null;
        System.gc();  //강제 Garbage Collection
        map.entrySet().stream().forEach(el -> System.out.println(el));
    }
}
```

결과
```
2000=test b
```

위 코드의 WeakHashMap을 HashMap으로 바꾼 경우에는 key1을 더 이상 사용하지 않음에도 불구하고
결과는
```
1000=test a
2000=test b
```
로 나오게 됩니다!


4. 책에서는 리스너와 콜백을 거의 동일시 얘기하고 있는 것 같습니다. 리스너 혹은 콜백이 메모리 누수의 주범이라고 얘기하고 있는데 이 부분은 예시가 없어서 저도 조금 어렵네요ㅠㅠ 좀 더 공부해보겠습니다.
