### ISSUE TITLE
[아이템 08] finalizer와 cleaner 사용을 피하라

### ISSUE THREAD

**Issue by kyupid** [java-piledrivers/effective-java#8]

**Comment by dunowljj** [comment]
42p 하단에 finalizer의 보안 문제의 전반적인 내용이 이해가 안가네요. 사실 저는 readObject와 readResolve 메서드도 생소한데 설명 부탁드려요!

**Comment by kyupid** [comment]
돈을 송금할 수 있는 Account 라는 객체가 있다고 칩시다
```java
public class Account {
	private String accountId;

	public Account(String accountId) {
		this.accountId = accountId;
	}

	public void transfer(BigDecimal amount, String to) {
		System.out.println("금액: " + amount)
		System.out.println("from: " + accountId)
		System.out.println("to: " + to)
	}
}

```
> 본문
> 생성자나 직렬화 과정에서 예외가 발생하면,

즉, Account 생성자에서 예외가 발생하도록 만들어봅시다.
```java
public class Account {
	private String accountId;

	public Account(String accountId) {
		this.accountId = accountId;

		if (accountId.equals("도둑놈")) {
			throw new IllegalArgumentException("도둑놈 잡았다! 👀");
		}
	}

	public void transfer(BigDecimal amount, String to) {
		System.out.println("금액: " + amount)
		System.out.println("from: " + accountId)
		System.out.println("to: " + to)
	}
}
```

이렇게 원래는 도둑놈이 오면 잡아야합니다.

그런데?

```java
public class BrokenAccount extends Account {
	public BrokenAccount(String accountId) {
		super(accountId);
	}

	@Override
	protected void finalize() throws Throwable {
		this.transfer(BigDecimal.valueOf(999999999), "도둑놈")
	}
}
```
이때도 도둑놈을 잡지못하지만

누가 악의적으로 코드로 exception을 try-catch로 잡아서 넘기고
 gc를 일으키면,,, finalize 메소드가 실행이됩니다

그래서 책에서 소개하는 방법은 Account를 상속해서 사용하지 못하도록 final를 붙여라는 것입니다.

class에 final을 붙여서 그렇게 할 수도 있지만, 만약에 꼭 Account를 open 해두어야한다면

Account에서 finalize를 override해서 아무 내용을 넣지말고 final을 넣어주면 그런 공격을 막을수있다는 내용입니다

---

readObject에 대한 내용은 직렬화에 대해서 공부해보시면 될 것 같아요.
이해하기 좋은 블로그 글 공유합니다 https://techblog.woowahan.com/2550/

읽어보시면 아시겠지만 readObject는 역직렬화할때 사용하는 메소드이고 IOException 을 throw합니다

똑같이 Account 예제처럼 Exception 잡아내면서 보안 공격의 위험성이 있습니다

---

레퍼런스: 백기선님 이펙티브 자바 강의
